
all:
	c++ -w -std=c++1y main.cpp assembly.cpp RLValue.cpp Statement.cpp SourceFile.cpp -o ncc


warn:
	c++ -Wall -std=c++1y main.cpp assembly.cpp RLValue.cpp Statement.cpp SourceFile.cpp -o ncc


clean:
	rm ncc


